version: 0.1.1
default:
  # Default profile created for data IO access.
  # API Keys
  SPORTSDATAIO_API_KEY: "{{ mage_secret_var('sportsdataio_api_key') }}"
  # Add your credentials for the source you use, and delete the rest.
  # AWS
  AWS_ACCESS_KEY_ID: "{{ mage_secret_var('aws_access_key_id') }}"
  AWS_SECRET_ACCESS_KEY: "{{ mage_secret_var('aws_secret_access_key') }}"
  #AWS_SESSION_TOKEN: session_token (Used to generate Redshift credentials)
  #AWS_REGION: region
  # Algolia
  ALGOLIA_APP_ID: app_id
  ALGOLIA_API_KEY: api_key
  ALGOLIA_INDEX_NAME: index_name
  # Azure
  AZURE_CLIENT_ID: "{{ env_var('AZURE_CLIENT_ID') }}"
  AZURE_CLIENT_SECRET: "{{ env_var('AZURE_CLIENT_SECRET') }}"
  AZURE_STORAGE_ACCOUNT_NAME: "{{ env_var('AZURE_STORAGE_ACCOUNT_NAME') }}"
  AZURE_TENANT_ID: "{{ env_var('AZURE_TENANT_ID') }}"
  # Chroma
  CHROMA_COLLECTION: collection_name
  CHROMA_PATH: path
  # Clickhouse
  CLICKHOUSE_DATABASE: default
  CLICKHOUSE_HOST: host.docker.internal
  CLICKHOUSE_INTERFACE: http
  CLICKHOUSE_PASSWORD: null
  CLICKHOUSE_PORT: 8123
  CLICKHOUSE_USERNAME: null
  # Druid
  DRUID_HOST: hostname
  DRUID_PASSWORD: password
  DRUID_PATH: /druid/v2/sql/
  DRUID_PORT: 8082
  DRUID_SCHEME: http
  DRUID_USER: user
  # DuckDB
  DUCKDB_DATABASE: database
  DUCKDB_SCHEMA: main
  # Google
  GOOGLE_SERVICE_ACC_KEY:
    type: service_account
    project_id: "personal-pgatour"
    private_key_id: "3e257da6b317adc6abc7a8b0bf1b0bee346ce952"
    private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDjWTQCN0MyzOrZ\nM/+1gxRox/s/5y/aFCEp3CjXMP1mrHqLDEGIRUxmpReR5NsZdjB8dLwWOcsFaU4W\nRYY2EMKt2BzUkMBFXti/sJvUIg22l+P6OwmAzmaDDZnKyH3utzU4DJpSrMjUyTM4\n4/LtHO20iPTKCiG8PVObFCtbOsejQCBeAoM4ND6KZ5NU0xtX54NFAPr9/aBwk5DH\nJUy84381mPvdUhDnEr0ZZAtlg440pVYiXiKKyOCn9pQG0IqY0llKbsMb7Oi97cMK\ncsHRhTEUA7jX1FMR3BEuiNXMj1O/XzkquXzH4qkaR4YYFMuzIAAz6Vsc48qNOug2\n6OocTLjhAgMBAAECggEAAwb8YviAE+cX9s3Ic+RLm0bpGOVn2mGLkivKUhiRkefD\nYffxz3IMyGPJDTpHk0Pi9WVLM93lJCyjdjcgHbbaFh0wlRawWLwglWeGoQErFD6w\nMcl4y5bz/9QTM4Nj7zp6okUYsPfNXM1TufLfGI/at8gIamr5dAY6XMWcpi8BhYed\n+EmsniS5ewaCE0CmH/qp8p2i2FN9AaaKFhzIz46dY+38q3+/G1ZN+AnukYLP8vnn\nKXrUvrzxSmM93rhXcGnhScosi6EaWyZeSI+a0o77QaYoYJrGordSaJ66Q5FnwbCr\nmCohA3mlhjEWLeSSSmM71nHhvK9TnLM5Ud82Pt1w+QKBgQD8WGj0spY8Vg9Y0k7z\n3RfDhHtgg8pgkE1wdW6zlCEEHvbUzL/8MPOGJobYrOc2i05//ZhnvZt8XZG2gogy\n863zuVncNXW46oJXbP7cl00MhZm0Cxa9g9tAiYsDvv3sOFVMCpAR8/9kFR/lQyhZ\n+dWlMLQ6fY+lhf91Cd+Hnib9ZwKBgQDmpB1+7gxrfnf6oQIWef5Q4U3ULmrKl3W6\nCndarCe0CO4/qWIvL744aZqGyKIsHJKj3iyIeJZna64gzcEoSpkLHXZkg2pIlsa4\nya8jXtkmhckOvuhw78za1MSmjMjy168APfgt7R474DVnoj8dvSVTrNkoFVYDYe03\nZsTmrMjidwKBgQDhrWO4K5smvMSe5/8KI1nkVrBMYbD1aTiIcc2eNsTMPbD8IV01\nesXf3MbOMtvZMP70gmTxqmXK9JejRNvvzXRtuv89bGYrCTemXmkT+RBEOZt7pEsj\nFDBaaGf14rKOtta52dx84d0usaHD1KraxQ+n24XjpXV5T/xlvH23eN5f0wKBgBzL\nZHtSUO6irWv26gHQXTXPyx2wZdjBLAt7/was85AAhW4hQYbOmRsF5CrrpYOIVa5r\nsHehRnXG9chWp8TV+2Ft3jgSSBSj7k9nrpvl3Yp3rXBP2UkwRw0S/zIj5Xqb/tcy\n5WcmcV3cUg6MLQETejOGIt5kO4bUlP8Tr4V1EOdlAoGBAPnq1ysgSkDbkNokUmLr\nmV6wWPoyNumLS0v5UEQH6TqP/4fyzLscIsWKJm5eTdDiA92gFAMBquyzu48kb3SH\nkMVV5lS5opDUSTGbMiW1I72pVg7dWJtj7STOtIhOa74PYWnGb0e9IQgHKrFTvhRC\ndhkmX2ktnJH5sKG5ZhJhjFpq\n-----END PRIVATE KEY-----\n"
    client_email: "kylereardon-project@personal-pgatour.iam.gserviceaccount.com"
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://oauth2.googleapis.com/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/kylereardon-project%40personal-pgatour.iam.gserviceaccount.com"
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/path/to/your/service/account/key.json"
  GOOGLE_LOCATION: US # Optional
  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://{username}:{password}@{host}:{port}/"
  MONGODB_HOST: host
  MONGODB_PORT: 27017
  MONGODB_USER: user
  MONGODB_PASSWORD: password
  MONGODB_DATABASE: database
  MONGODB_COLLECTION: collection
  # MSSQL
  MSSQL_DATABASE: database
  MSSQL_SCHEMA: schema
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: host
  MSSQL_PASSWORD: password
  MSSQL_PORT: 1433
  MSSQL_USER: SA
  # MySQL
  MYSQL_DATABASE: database
  MYSQL_HOST: host
  MYSQL_PASSWORD: password
  MYSQL_PORT: 3306
  MYSQL_USER: root
  # Pinot
  PINOT_HOST: hostname
  PINOT_PASSWORD: password
  PINOT_PATH: /query/sql
  PINOT_PORT: 8000
  PINOT_SCHEME: http
  PINOT_USER: user
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: postgres
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: username
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: hostname
  POSTGRES_PORT: 5432
  # Qdrant
  QDRANT_COLLECTION: collection
  QDRANT_PATH: path
  # Redshift
  REDSHIFT_SCHEMA: public # Optional
  REDSHIFT_DBNAME: redshift_db_name
  REDSHIFT_HOST: redshift_cluster_id.identifier.region.redshift.amazonaws.com
  REDSHIFT_PORT: 5439
  REDSHIFT_TEMP_CRED_USER: temp_username
  REDSHIFT_TEMP_CRED_PASSWORD: temp_password
  REDSHIFT_DBUSER: redshift_db_user
  REDSHIFT_CLUSTER_ID: redshift_cluster_id
  REDSHIFT_IAM_PROFILE: default
  # Snowflake
  SNOWFLAKE_USER: username
  SNOWFLAKE_PASSWORD: password
  SNOWFLAKE_ACCOUNT: account_id.region
  SNOWFLAKE_DEFAULT_WH: null                  # Optional default warehouse
  SNOWFLAKE_DEFAULT_DB: null                  # Optional default database
  SNOWFLAKE_DEFAULT_SCHEMA: null              # Optional default schema
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: null      # Optional private key passphrase
  SNOWFLAKE_PRIVATE_KEY_PATH: null            # Optional private key path
  SNOWFLAKE_ROLE: null                        # Optional role name
  SNOWFLAKE_TIMEOUT: null                     # Optional timeout in seconds
  # Trino
  trino:
    catalog: postgresql                       # Change this to the catalog of your choice
    host: 127.0.0.1
    http_headers:
      X-Something: 'mage=power'
    http_scheme: http
    password: mage1337                        # Optional
    port: 8080
    schema: core_data
    session_properties:                       # Optional
      acc01.optimize_locality_enabled: false
      optimize_hash_generation: true
    source: trino-cli                         # Optional
    user: admin
    verify: /path/to/your/ca.crt              # Optional
  # Weaviate
  WEAVIATE_ENDPOINT: https://some-endpoint.weaviate.network
  WEAVIATE_INSTANCE_API_KEY: YOUR-WEAVIATE-API-KEY
  WEAVIATE_INFERENCE_API_KEY: YOUR-OPENAI-API-KEY
  WEAVIATE_COLLECTION: collectionn_name
